# ------------------------------------------------------------------------------------
# 메시지 세팅
# ------------------------------------------------------------------------------------
messages:
  # 접두사
  prefix: '&3[아이템자랑] &r'

  # 콘피그를 성공적으로 다시 불러왔을 때 출력되는 메시지
  reloadConfig: "&a콘피그를 다시 불러왔습니다."

  # 플레이어가 손에 아이템을 들고 아이템 자랑을 했을 때 출력되는 메시지
  itemInHand: "&6{item}"

  # 플레이어가 손에 아무것도 들지 않고 아이템 자랑을 했을 때 출력되는 메시지
  noItemInHand: "&6{player}&f님의 &c왕주먹&r"

# ------------------------------------------------------------------------------------
# 오류 메세지 세팅
# ------------------------------------------------------------------------------------
errorMessages:

  # 명령어를 실행할 때 권한이 없을 경우 출력되는 메시지
  noPermission: "&c당신은 해당 명령어를 사용할 권한이 없습니다."

  # 콘솔에서 명령어를 사용할 경우 출력되는 메시지
  noConsole: "&c해당 명령어를 콘솔에서 사용할 수 없습니다."

  # 올바르지 않는 명령어를 사용할 경우 출력되는 메시지
  wrongCommand: "&c올바르지 않은 명령어입니다."